[package]
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"
name = "engine"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "=0.2.64", features = ["nightly"] }
rand = "0.7.3"
rand_pcg = "0.2.1"
slab = "0.4"
fnv = "1.0.7"
base64 = "0.12"
bincode = "1.3"
serde = "1.0.114"
serde_derive = "1.0.114"
serde_json = "1.0.56"
wasm-logger = "0.2.0"
# Disable logging staticly in release, making all log calls into no-ops
log = { version = "0.4", features = ["release_max_level_off"] }
console_error_panic_hook = "0.1.6"
uuid = { version = "0.8", features = ["serde"] }

common = { path = "../common" }
polysynth = { path = "../polysynth" }
