max_width = 100
comment_width = 100
condense_wildcard_suffixes = true
fn_single_line = true
# where_single_line = true
format_strings = true
merge_imports = true
match_block_trailing_comma = true
reorder_impl_items = true
report_todo = "Always"
report_fixme = "Always"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
match_arm_blocks = false
overflow_delimited_expr = true
edition = "2018"
normalize_doc_attributes = true
