[package]
name = "web-synth-backend"
version = "0.1.0"
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"

[dependencies]
dotenv = "0.13.0"

diesel = "1.4.2"

lazy_static = "1.3.0"

mysql = "15.1.0"
r2d2 = "0.8.4"
r2d2_mysql = "15.0.0"

rocket = "0.4.0"

serde_json = "1.0.39"
serde = "1.0.90"
serde_derive = "1.0.90"
