[package]
name = "web-synth-backend"
version = "0.1.0"
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"

diesel = "1.4.5"

hex = "0.4"

itertools = "0.10"

lazy_static = "1.4.0"

chrono = "0.4.19"
log = "0.4.11"
hound = "3.4"

rayon = "1.5"

reqwest = { version = "0.11", features = ["gzip", "brotli"] }

rocket = { git = "https://github.com/SergioBenitez/Rocket.git", rev = "693f4f9ee50057fc735e6e7037e6dee5b485ba10", features = ["json"] }
rocket_sync_db_pools = { git = "https://github.com/SergioBenitez/Rocket.git", rev = "693f4f9ee50057fc735e6e7037e6dee5b485ba10", features = ["diesel_mysql_pool"]}
rocket_async_compression = { git = "https://github.com/ameobea/rocket_async_compression.git" }

serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"

sha2 = "0.9"

tokio = { version = "1.4", features = ["macros", "rt-multi-thread"] }
