[package]
name = "web-synth-backend"
version = "0.1.0"
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"

diesel = "1.4.5"

hex = "0.4"

lazy_static = "1.4.0"

chrono = "0.4.19"
fern = "0.6"
log = "0.4.11"

rayon = "1.5"

reqwest = "0.10"

rocket = { git = "https://github.com/ameobea/Rocket.git" }
rocket_contrib = { git = "https://github.com/ameobea/Rocket.git", features = ["json", "diesel_mysql_pool", "compression"] }

serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"

sha2 = "0.9"

tokio = { version = "0.2", features = ["full"] }
