[package]
name = "web-synth-backend"
version = "0.1.0"
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"

diesel = "1.4.3"

lazy_static = "1.4.0"

chrono = "0.4.10"
fern = "0.5.9"
log = "0.4.8"

rayon = "1.3.0"

rocket = "0.4.2"
rocket_contrib = { version = "0.4.2", features = ["json", "diesel_mysql_pool"] }

serde_json = "1.0.44"
serde = "1.0.104"
serde_derive = "1.0.104"
