[package]
name = "web-synth-backend"
version = "0.1.0"
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"

diesel = "1.4.5"

lazy_static = "1.4.0"

chrono = "0.4.19"
fern = "0.6"
log = "0.4.11"

rayon = "1.4"

rocket = "0.4.5"
rocket_contrib = { version = "0.4.5", features = ["json", "diesel_mysql_pool"] }

serde_json = "1.0.58"
serde = "1.0.116"
serde_derive = "1.0.116"
