[package]
name = "web-synth-backend"
version = "0.1.0"
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"

[dependencies]
dotenv = "0.13.0"

diesel = "1.4.2"

lazy_static = "1.3.0"

rocket = "0.4.0"
rocket_contrib = { version = "0.4.0", features = ["json", "diesel_mysql_pool"] }

serde_json = "1.0.39"
serde = "1.0.90"
serde_derive = "1.0.90"
