[development]
address = "localhost"
port = 7467
keep_alive = 5
log = "normal"
limits = { forms = 32000768 }

[staging]
address = "0.0.0.0"
port = 7467
keep_alive = 5
log = "normal"
limits = { forms = 32000768 }

[production]
address = "0.0.0.0"
port = 7467
keep_alive = 5
log = "normal"
limits = { forms = 32000768 }
