[package]
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"
name = "engine"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "=0.2.25"
rand = "0.5.5"
rand_pcg = "0.1.1"
slab = "0.4"
fnv = "1.0.6"
base64 = "0.10.0"
bincode = "1.0.1"
serde = "1.0.80"
serde_derive = "1.0.80"

common = { git = "https://github.com/Ameobea/sketches.git" }

[profile.dev]
opt-level = 1
debug-assertions = true

[profile.release]
opt-level = 3
debug-assertions = false
codegen-units = 1
