[package]
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"
name = "web-synth-engine"
version = "0.1.0"

[workspace]
members = ["engine", "common", "midi", "polysynth", "spectrum_viz"]

[profile.dev]
opt-level = 1
debug-assertions = true
debug = true

[profile.release]
opt-level = 3
debug-assertions = false
codegen-units = 1
panic = "abort"
debug = false
