[package]
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"
name = "engine"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.54"
rand = "0.7.2"
rand_pcg = "0.2.1"
slab = "0.4"
fnv = "1.0.6"
base64 = "0.11.0"
bincode = "1.2"
serde = "1.0.102"
serde_derive = "1.0.102"
serde_json = "1.0.41"
wasm-logger = "0.2.0"
log = "0.4"
console_error_panic_hook = "0.1.6"
uuid = { version = "0.8", features = ["serde"] }

common = { path = "./libs/common" }
polysynth = { path = "./libs/polysynth" }

[profile.dev]
opt-level = 1
debug-assertions = true

[profile.release]
opt-level = 3
debug-assertions = false
codegen-units = 1
