[package]
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"
name = "engine"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "=0.2.43"
rand = "0.5.5"
rand_pcg = "0.1.1"
slab = "0.4"
fnv = "1.0.6"
base64 = "0.10.0"
bincode = "1.0.1"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.39"
wasm-logger = "0.1.2"
log = "0.4"
console_error_panic_hook = "0.1.6"
uuid = { version = "0.7.4", features = ["serde"] }

[profile.dev]
opt-level = 1
debug-assertions = true

[profile.release]
opt-level = 3
debug-assertions = false
codegen-units = 1
