[package]
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"
name = "engine"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.25"
rand = "0.5.5"
rand_pcg = "0.1.1"
slab = "0.4"
fnv = "1.0.6"

common = { path="../../common" }
