[package]
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"
name = "engine"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen.git", rev = "fb0bbc00" }
rand = "0.5.5"
rand_pcg = "0.1.1"
slab = "0.4"
fnv = "1.0.6"
base64 = "0.10.0"
bincode = "1.1.4"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.39"
wasm-logger = { git = "https://gitlab.com/Ameobea/wasm-logger.git" }
log = "0.4"
console_error_panic_hook = { git = "https://github.com/Ameobea/console_error_panic_hook.git" }
uuid = { version = "0.7.4", features = ["serde"] }

common = { path = "./libs/common" }

[profile.dev]
opt-level = 1
debug-assertions = true

[profile.release]
opt-level = 3
debug-assertions = false
codegen-units = 1
