max_width = 100
comment_width = 100
condense_wildcard_suffixes = true
fn_single_line = true
# where_single_line = true
format_strings = true
imports_granularity="Crate"
match_block_trailing_comma = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
match_arm_blocks = false
overflow_delimited_expr = true
edition = "2021"
normalize_doc_attributes = true
tab_spaces = 2
