[package]
name = "event_scheduler"
version = "0.1.0"
authors = ["Casey Primozic <casey@cprimozic.net>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
heapless = "0.5"
float-ord = "0.2"
