ALTER TABLE voice_presets ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE voice_presets SET created_at = NULL;

ALTER TABLE wavetable_presets ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE wavetable_presets SET created_at = NULL;

ALTER TABLE synth_presets ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE synth_presets SET created_at = NULL;

ALTER TABLE subgraph_presets ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE subgraph_presets SET created_at = NULL;

ALTER TABLE midi_compositions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE midi_compositions SET created_at = NULL;

ALTER TABLE looper_presets ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE looper_presets SET created_at = NULL;
