[package]
authors = ["Casey Primozic <casey@cprimozic.net>"]
edition = "2021"
name = "adsr"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dsp = {path = "../dsp" }

[features]
exports = []
default = ["exports"] # TODO REVERT
