[package]
name = "oscilloscope"
version = "0.1.0"
authors = ["Casey Primozic <casey@cprimozic.net>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dsp = { path = "../dsp" }
canvas_utils = { path = "../canvas_utils" }
common = { path = "../common" }
