[package]
name = "noise_gen"
version = "0.1.0"
authors = ["Casey Primozic <casey@cprimozic.net>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rand_pcg = "0.3"
rand = "0.7"
common = { path = "../common", default_features = false}
dsp = { path = "../dsp" }
