launch-jupyter:
  #!/usr/bin/env zsh

  id="$(docker run -d --rm --net host -v "${PWD}":/home/jovyan/work --user root --memory-swap -1 -e GRANT_SUDO=yes jupyter/tensorflow-notebook:latest)"
  echo "Launched docker container with id=${id}"
  sleep 1
  echo "$((docker logs $id) 2>&1 | grep token | head -n 1)"
