[package]
name = "granular"
version = "0.1.0"
authors = ["Casey Primozic <casey@cprimozic.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dsp = { path = "../dsp" }
common = { path = "../common", default_features = false }
rand = "0.7"
hound = "3.4"
claxon = "0.4"
