name: Cypress Tests

on: [push]

jobs:
  # https://github.com/marketplace/actions/cypress-io
  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Set up build environment + toolchains with Rust nightly with Wasm support and NodeJS
      - name: Install minimal Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2019-11-25
      - name: Use Rust nightly
        run: rustup default nightly-2019-11-25
      - uses: actions/setup-node@v1
        with:
          node-version: '13.1'
      - name: Install Rust Wasm support
        run: rustup target add wasm32-unknown-unknown

      # Caching
      - name: Cache cargo binaries
        id: cache-cargo-binaries
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}_nightly-2019-11-25_cargo-registry_just-0.5.1_wasm-bindgen-cli-0.2.54
      - name: Cache `engine` lib build artifacts
        uses: actions/cache@v1
        with:
          path: ./engine/target
          key: ${{ runner.os }}_nightly-2019-11-25_${{ hashFiles('engine/src/**') }}_${{ hashFiles('engine/Cargo.lock') }}
      - name: Cache `midi` lib build artifacts
        uses: actions/cache@v1
        with:
          path: ./engine/libs/midi/target
          key: ${{ runner.os }}_nightly-2019-11-25_${{ hashFiles('engine/libs/midi/src/**') }}_${{ hashFiles('engine/libs/midi/Cargo.lock') }}
      - name: Cache `polysynth` lib build artifacts
        uses: actions/cache@v1
        with:
          path: ./engine/libs/polysynth/target
          key: ${{ runner.os }}_nightly-2019-11-25_${{ hashFiles('engine/libs/polysynth/src/**') }}_${{ hashFiles('engine/libs/polysynth/Cargo.lock') }}
      - name: Cache `spectrum_viz` lib build artifacts
        uses: actions/cache@v1
        with:
          path: ./engine/libs/spectrum_viz/target
          key: ${{ runner.os }}_nightly-2019-11-25_${{ hashFiles('engine/libs/spectrum_viz/src/**') }}_${{ hashFiles('engine/libs/spectrum_viz/Cargo.lock') }}
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ hashFiles('yarn.lock') }}

      # Install Cargo binaries used during the build process
      - name: Install `just`
        if: steps.cache-cargo-binaries.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: just -v 0.5.1
      - name: Install `wasm-bindgen-cli`
        if: steps.cache-cargo-binaries.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-bindgen-cli -v 0.2.54

      # Build all Rust modules into Wasm, run `wasm-bindgen`, compile JavaScript, and link everything together
      - name: Install node modules
        run: yarn
      - name: Build all wasm + javascript
        run: just build-all
      # Run Cypress tests
      # - name: Cypress Run
      #   uses: cypress-io/github-action@v1.16.1
      #   with:
      #     browser: chrome
