name: Cypress Tests

on: [push]

jobs:
  # https://github.com/marketplace/actions/cypress-io
  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: docker.pkg.github.com/ameobea/web-synth/ci-builder:latest
      - name: Cache cargo binaries
        id: cache-cargo-binaries
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-registry-just-0.5.1-wasm-bindgen-cli-0.2.54
      - name: Install `just`
        if: steps.cache-cargo-binaries.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: just -v 0.5.1
      - name: Install `wasm-bindgen-cli`
        if: steps.cache-cargo-binaries.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-bindgen-cli -v 0.2.54
      - uses: actions/setup-node@v1
        with:
          node-version: '13.1'
      - name: Build all wasm + javascript
        run: just build-all
      - name: Cypress Run
        uses: cypress-io/github-action@v1.16.1
        with:
          browser: chrome
